/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package maquinadeheladosv7;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MiniN
 */
public class Maquina extends javax.swing.JFrame {

    /**
     * Creates new form Maquina
     */
    public Maquina() {
        this.monedero = 0d;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        titulo = new java.awt.Label();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        v_tabla = new javax.swing.JTable();
        v_error = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        v_insertar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        v_comprar = new javax.swing.JButton();
        v_cero = new javax.swing.JButton();
        v_ocho = new javax.swing.JButton();
        v_nueve = new javax.swing.JButton();
        v_siete = new javax.swing.JButton();
        v_cuatro = new javax.swing.JButton();
        v_cinco = new javax.swing.JButton();
        v_seis = new javax.swing.JButton();
        v_tres = new javax.swing.JButton();
        v_dos = new javax.swing.JButton();
        v_uno = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        v_dinero = new javax.swing.JLabel();
        botonVentas = new javax.swing.JButton();
        LabelPosicion = new javax.swing.JLabel();
        botonApagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        titulo.setAlignment(java.awt.Label.CENTER);
        titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titulo.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        titulo.setName("titulo"); // NOI18N
        titulo.setText("Maquina De Helados");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        v_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Posicion", "Nombre", "Tipo", "Precio", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        v_tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v_tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(v_tabla);

        v_error.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        v_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        v_error.setText(".");

        v_insertar.setBackground(new java.awt.Color(0, 0, 0));
        v_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_insertarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(v_insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 13, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(v_insertar, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addContainerGap())
        );

        v_comprar.setText(">");
        v_comprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                v_comprarMouseClicked(evt);
            }
        });

        v_cero.setText("0");
        v_cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_ceroActionPerformed(evt);
            }
        });

        v_ocho.setText("8");
        v_ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_ochoActionPerformed(evt);
            }
        });

        v_nueve.setText("9");
        v_nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_nueveActionPerformed(evt);
            }
        });

        v_siete.setText("7");
        v_siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_sieteActionPerformed(evt);
            }
        });

        v_cuatro.setText("4");
        v_cuatro.setToolTipText("");
        v_cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_cuatroActionPerformed(evt);
            }
        });

        v_cinco.setText("5");
        v_cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_cincoActionPerformed(evt);
            }
        });

        v_seis.setText("6");
        v_seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_seisActionPerformed(evt);
            }
        });

        v_tres.setText("3");
        v_tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_tresActionPerformed(evt);
            }
        });

        v_dos.setText("2");
        v_dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_dosActionPerformed(evt);
            }
        });

        v_uno.setText("1");
        v_uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_unoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(v_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(v_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(v_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(v_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(v_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(v_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(v_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(v_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(v_cero, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(v_nueve, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                    .addComponent(v_comprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(v_cero, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(v_comprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        v_dinero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        v_dinero.setText("Dinerito");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(v_dinero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(v_dinero, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        botonVentas.setText("VENTAS");
        botonVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonVentasMouseClicked(evt);
            }
        });
        botonVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVentasActionPerformed(evt);
            }
        });

        LabelPosicion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelPosicion.setText("Posicion");

        botonApagar.setText("Apagar");
        botonApagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonApagarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v_error, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelPosicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(botonVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188)
                        .addComponent(botonApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LabelPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(v_error)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                            .addComponent(botonApagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        DefaultTableModel miTabla = (DefaultTableModel) this.v_tabla.getModel();
        Object[] datos = new Object[5];
        try (HeladoDAOImplementation heladoDAO = new HeladoDAOImplementation()) {
            ArrayList<Helado> helados = (ArrayList) heladoDAO.getHelados();

            for (Helado helado : helados) {
                datos[0] = helado.getPosicion();
                datos[1] = helado.getNombre();
                datos[2] = helado.getTipo();
                datos[3] = helado.getPrecio();
                datos[4] = helado.getCantidad();
                miTabla.addRow(datos);
            }

        } catch (Exception e) {
            System.out.println(e.getClass() + " " + e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (monedero > 0) {
            RetirarDinero retirar = new RetirarDinero(this, true);

            retirar.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosing

    private void v_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_insertarActionPerformed
        // TODO add your handling code here:
        Money monedas = new Money(this, true);
        monedas.setVisible(true);
    }//GEN-LAST:event_v_insertarActionPerformed

    private void v_sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_sieteActionPerformed
        // TODO add your handling code here:
        LabelPosicion.setText("Posicion: ");
        LabelPosicion.setText(LabelPosicion.getText() + "7");
        this.posicion = 7;
    }//GEN-LAST:event_v_sieteActionPerformed

    private void v_ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_ochoActionPerformed
        // TODO add your handling code here:
        LabelPosicion.setText("Posicion: ");
        LabelPosicion.setText(LabelPosicion.getText() + "8");
        this.posicion = 8;

    }//GEN-LAST:event_v_ochoActionPerformed

    private void v_dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_dosActionPerformed
        // TODO add your handling code here:
        LabelPosicion.setText("Posicion: ");
        LabelPosicion.setText(LabelPosicion.getText() + "2");
        this.posicion = 2;
    }//GEN-LAST:event_v_dosActionPerformed

    private void v_tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_tresActionPerformed
        // TODO add your handling code here:
        LabelPosicion.setText("Posicion: ");
        LabelPosicion.setText(LabelPosicion.getText() + "3");
        this.posicion = 3;
    }//GEN-LAST:event_v_tresActionPerformed

    private void v_unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_unoActionPerformed
        // TODO add your handling code here:
        LabelPosicion.setText("Posicion: ");
        LabelPosicion.setText(LabelPosicion.getText() + "1");
        this.posicion = 1;
    }//GEN-LAST:event_v_unoActionPerformed

    private void v_seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_seisActionPerformed
        // TODO add your handling code here:
        LabelPosicion.setText("Posicion: ");
        LabelPosicion.setText(LabelPosicion.getText() + "6");
        this.posicion = 6;
    }//GEN-LAST:event_v_seisActionPerformed

    private void v_nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_nueveActionPerformed
        // TODO add your handling code here:
        LabelPosicion.setText("Posicion: ");
        LabelPosicion.setText(LabelPosicion.getText() + "9");
        this.posicion = 9;
    }//GEN-LAST:event_v_nueveActionPerformed

    private void v_cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_cuatroActionPerformed
        // TODO add your handling code here:
        LabelPosicion.setText("Posicion: ");
        LabelPosicion.setText(LabelPosicion.getText() + "4");
        this.posicion = 4;
    }//GEN-LAST:event_v_cuatroActionPerformed

    private void v_cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_cincoActionPerformed
        // TODO add your handling code here:
        LabelPosicion.setText("Posicion: ");
        LabelPosicion.setText(LabelPosicion.getText() + "5");
        this.posicion = 5;
    }//GEN-LAST:event_v_cincoActionPerformed

    private void v_ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_ceroActionPerformed
        // TODO add your handling code here:
        LabelPosicion.setText("Posicion: ");
        LabelPosicion.setText(LabelPosicion.getText() + "0");
        this.posicion = 0;
    }//GEN-LAST:event_v_ceroActionPerformed

    private void v_tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v_tablaMouseClicked
        // TODO add your handling code here:
        int filaClicked = this.v_tabla.rowAtPoint(evt.getPoint());

        Helado helado = null;
        this.posicion = (Integer) this.v_tabla.getValueAt(filaClicked, 0);
        this.LabelPosicion.setText("Posicion: " + posicion);
    }//GEN-LAST:event_v_tablaMouseClicked

    private void botonVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVentasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVentasMouseClicked

    private void botonVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVentasActionPerformed
        VentasJFrame ventas = new VentasJFrame(this, true);

        ventas.setVisible(true);
    }//GEN-LAST:event_botonVentasActionPerformed

    private void v_comprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_v_comprarMouseClicked
        /////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        Helado helado = null;

        try (HeladoDAOImplementation heladoDAO = new HeladoDAOImplementation(); VentasDAOImplementation ventaDAO = new VentasDAOImplementation()) {

            helado = heladoDAO.obtenerHelado(this.posicion);

            if (helado != null) {
                if (!(helado.getPrecio() >= monedero)) {

                    if (!(helado.getCantidad() > 0)) {
                        v_error.setText("No hay suficiente dinero o no queda de ese helado");
                    } else {
                        heladoDAO.updateCantidad(helado.getCantidad() - 1, this.posicion);
//                        System.out.println(helado.getPosicion() + " cantidad: " + helado.getCantidad());
                        ventaDAO.setVenta(this.posicion);
                        monedero = monedero - helado.getPrecio();
                        v_dinero.setText(monedero + "");
                        v_error.setText("");
                    }

                } else {
                    v_error.setText("No hay suficiente dinero o no queda de ese helado");
                }
            }

        } catch (Exception e) {
            System.out.println(e.getClass() + " " + e.getMessage());
        }

        DefaultTableModel miTabla = (DefaultTableModel) this.v_tabla.getModel();
        miTabla.setNumRows(0);
        Object[] datos = new Object[5];

        try (HeladoDAOImplementation heladoDAO = new HeladoDAOImplementation()) {
            ArrayList<Helado> helados = (ArrayList) heladoDAO.getHelados();

            for (Helado heladito : helados) {
                datos[0] = heladito.getPosicion();
                datos[1] = heladito.getNombre();
                datos[2] = heladito.getTipo();
                datos[3] = heladito.getPrecio();
                datos[4] = heladito.getCantidad();
                miTabla.addRow(datos);
            }

        } catch (Exception e) {
            System.out.println(e.getClass() + " " + e.getMessage());
        }
    }//GEN-LAST:event_v_comprarMouseClicked

    private void botonApagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonApagarMouseClicked
        // TODO add your handling code here:
        if (monedero > 0) {
            RetirarDinero retirar = new RetirarDinero(this, true);
            retirar.setVisible(true);

            if (monedero <= 0) {
                this.dispose();
            }

        } else {
            this.dispose();
        }
    }//GEN-LAST:event_botonApagarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maquina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelPosicion;
    private javax.swing.JButton botonApagar;
    private javax.swing.JButton botonVentas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label titulo;
    private javax.swing.JButton v_cero;
    private javax.swing.JButton v_cinco;
    private javax.swing.JButton v_comprar;
    private javax.swing.JButton v_cuatro;
    private javax.swing.JLabel v_dinero;
    private javax.swing.JButton v_dos;
    private javax.swing.JLabel v_error;
    private javax.swing.JButton v_insertar;
    private javax.swing.JButton v_nueve;
    private javax.swing.JButton v_ocho;
    private javax.swing.JButton v_seis;
    private javax.swing.JButton v_siete;
    private javax.swing.JTable v_tabla;
    private javax.swing.JButton v_tres;
    private javax.swing.JButton v_uno;
    // End of variables declaration//GEN-END:variables
    private Double monedero;
    private int posicion;

    public double getMonedero() {
        return monedero;
    }

    public void setMonedero(double monedero) {
        this.monedero = monedero;
    }

    public void anadir5cents() {
        monedero += 0.05;
        v_dinero.setText(monedero + "");
    }

    public void anadir10cents() {
        monedero += 0.10;
        v_dinero.setText(monedero + "");
    }

    public void anadir20cents() {
        monedero += 0.20;
        v_dinero.setText(monedero + "");
    }

    public void anadir50cents() {
        monedero += 0.50;
        v_dinero.setText(monedero + "");
    }

    public void anadir1euro() {
        monedero += 1;
        v_dinero.setText(monedero + "");
    }

    public void anadir2euro() {
        monedero += 2;
        v_dinero.setText(monedero + "");
    }

    public void Retirar() {
        monedero = 0d;
        v_dinero.setText(monedero + "");
    }
}
